FROM node:22-alpine AS base

WORKDIR /backend

COPY ../nest/ /backend

# setup for bufferutil and utf-8-validate to suitable with socket.io
RUN apk add --no-cache python3 python3-dev py3-pip build-base
RUN ln -sf python3 /usr/bin/python

CMD npm install && npm run start:dev 