version: "3.8"

services:
  frontend:
    container_name: next
    build:
      context: .
      dockerfile: next/Dockerfile
    volumes:
      - ./next:/frontend
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - chat_bot_network

  pg:
    image: postgres
    hostname: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./config/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chat_bot_network

  app:
    container_name: nest
    build:
      context: .
      dockerfile: nest/Dockerfile
    volumes:
      - ./nest:/backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - pg
    networks:
      - chat_bot_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./config/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - pg
    networks:
      - chat_bot_network

networks:
  chat_bot_network:
    driver: bridge
