version: "3.8"

services:
  frontend:
    container_name: next
    build:
      context: .
      dockerfile: next/Dockerfile
    volumes:
      - ./next:/usr/src/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /usr/src/app

  pg:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - ./config/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: nest_be
    build:
      context: .
      dockerfile: nest/Dockerfile
    volumes:
      - ./next:/backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - pg

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - pg
